sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - docker build -t map_nearby_places .
  - docker run -ti -p 8000:8000 -d --name map_nearby_places map_nearby_places

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - docker ps | grep map_nearby_places
  - coverage run --source . testrunner.py ./tests

after_success:
  coveralls